# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IEVsnhxYgDqvWcoki5FUHCYS9IPyx_-v
"""

with open("input3.txt", "r") as file:
    l = file.readline()
    output = open("output3.txt", "w")
    dic = {}
    for i in range(int(l)):
      z = file.readline().split(" ")
      dic[int(z[0])] = int(z[1])
    sorted_dict = dict(sorted(dic.items(), key=lambda x:x[1]))
    count= 1
    dic1 = {}
    for k,v in sorted_dict.items():
      max_k = k
      max_v = v
      dic1[k] = v
      for k,v in sorted_dict.items():
        if k>=max_k and k>=max_v:
          dic1[k] = v
          count+=1
          max_k = k
          max_v = v
      break
    output.write(str(count))
    output.write("\n")
    for k,v in dic1.items():
      output.write(str(k) + " "+ str(v))
      output.write("\n")