# -*- coding: utf-8 -*-
"""task1 (1) lab 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A0Yk4B_5QTBtMTuhzbfCfyExilRpcGrM
"""

#1(1)
with open("input1(1).txt","r") as file:
  output =open("output(1).txt","w")
  num = file.readline().split()
  len = int(num[0])
  target= int(num[1])
  z= file.readline().split()
  flag = False
  left = 0
  right = 0
  for i in range(len):
    for j in range(len-1):
      sum=int(z[i])+int(z[j])
      if sum == target:
        flag = True
        left = i+1
        right = j+1
  if flag == False:
    output.write("IMPOSSIBLE")
  else:
    output.write(f"{str(right)} {str(left)}")