# -*- coding: utf-8 -*-
"""task1 (2) lab 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BNT3LFQzwEKy4scz2rfc8K-R18vFc4dr
"""

with open("input1(2).txt","r") as file:
  output =open("output1(2).txt","w")
  num = file.readline().split()
  len = int(num[0])
  target= int(num[1])
  z= file.readline().split()
  left = 0
  right = len-1
  flag = False
  while left<right:
    sum = int(z[left])+int(z[right])
    if sum == target:
      flag = True
      output.write(f"{str(left+1)} {str(right+1)}")
      break
    if sum > target:
      right-=1
    if sum <target:
      left+=1
  if flag == False:
    output.write("IMPOSSIBLE")