# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15UjrcKbnmRoSwLmVaYvL1_SpkA9aRcM1
"""

with open("input3.txt","r") as file:
  length = file.readline()
  arr = file.readline().split(" ")
  for i in range(len(arr)):
    arr[i] = int(arr[i])
  count=0
  for i in range(len(arr)):
    for j in range(i+1,len(arr)):
      if j>i and arr[i]> arr[j]:
        count+=1
  with open("output3.txt","w") as file:
    file.write(f"{count}")