# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11-9OWFKiozDzsE85V-SnR9_GzwVM1DSS
"""

def partition(array, low, high):
  pivot = array[high]
  i = low - 1
  for j in range(low, high):
    if array[j] <= pivot:
      i = i + 1
      (array[i], array[j]) = (array[j], array[i])
  (array[i + 1], array[high]) = (array[high], array[i + 1])
  return i + 1

def quickSort(array, low, high):
  if low < high:
    pi = partition(array, low, high)
    quickSort(array, low, pi - 1)
    quickSort(array, pi + 1, high)
with open("input5.txt","r") as file:
  z = file.readline()
  arr= file.readline().split(" ")
  for i in range(len(arr)):
    arr[i] = int(arr[i])
  sorted_array = quickSort(arr,0,len(arr)-1)
  with open("ouput5.txt","w") as file:
    for i in arr:
      file.write(f"{i} ")