# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o9113s4bm6PHxCWyG9azy0nGNxku8Vel
"""

def merge(a,b):
  me_list= a+b
  i=0
  j=i+1
  max=0
  while i<len(me_list)-1:
    sum = (me_list[i])+ (me_list[j])**2
    if sum>max:
      max=sum
    if j==len(me_list)-1:
      i=i+1
      j=i+1
    else:
      j=j+1
  if len(me_list)==z:
    return max
  else:
    return me_list

def mergesort(arr):
  if len(arr)<=1:
    return arr
  mid=len(arr)//2
  a1=mergesort(arr[0:mid])
  a2=mergesort(arr[mid:])
  sorted_arr=merge(a1,a2)
  return sorted_arr

with open("input4.txt","r") as file:
  z = file.readline()
  z= int(z)
  arr= file.readline().split(" ")
  for i in range(len(arr)):
    arr[i] = int(arr[i])
  sorted_arr = mergesort(arr)
with open("output.txt","w") as file:
  file.write(str(sorted_arr))