# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HYTdCWzOe7GQJZdtOrnmFGm2wlAZm7Ab
"""

with open("input6.txt","r") as file:
  z = file.readline()
  arr= file.readline().split(" ")
  for i in range(len(arr)):
    arr[i] = int(arr[i])
  length_q = file.readline()
  length_q = int(length_q[0])
  query = []
  for i in range(length_q):
    z = file.readline()
    query.append(int(z))
  def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]

    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1

def kth_smallest(arr, low, high, k):
    pivot_index = partition(arr, low, high)
    if pivot_index == k - 1:
        return arr[pivot_index]
    elif pivot_index > k - 1:
        return kth_smallest(arr, low, pivot_index - 1, k)
    else:
        return kth_smallest(arr, pivot_index + 1, high, k)

def find_kth_smallest_values(arr, queries):
    result = []
    for k in queries:
        result.append(kth_smallest(arr, 0, len(arr) - 1, k))
    return result
result = find_kth_smallest_values(arr, query)
with open("output6.txt","w") as file:
  for i in result:
    file.write(f"{i} \n")