# -*- coding: utf-8 -*-
"""task2 lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uCXyIe7-PZ_6KajmmsBLVsFvlqWrBAne
"""

def max_num(arr):
  if len(arr)<=1:
    return arr[0]
  mid=len(arr)//2
  a1=max_num(arr[0:mid])
  a2=max_num(arr[mid:])
  if a1>=a2:
    return a1
  else:
    return a2

with open("input2.txt","r") as file:
  length = file.readline()
  arr = file.readline().split(" ")
  for i in range(len(arr)):
    arr[i] = int(arr[i])
  maxi = max_num(arr)
  with open("output2.txt","w") as file:
    file.write(f"{maxi}")

#The time complexity of this code is O(nlogn)