# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11f75aPy8f4qCs7fayAy78E-4QrIkbetw
"""

def merge(a, b):
  i = 0
  j = 0
  l = []
  while i < len(a) and j < len(b):
    if a[i] <= b[j]:
      l.append(a[i])
      i += 1
    else:
      l.append(b[j])
      j += 1
  if i < len(a):
      l += a[i:]
  if j < len(b):
      l += b[j:]
  return l


def mergeSort(arr):
    if len(arr) <= 1:
        return arr
    else:
        mid = len(arr)//2
        a1 = mergeSort(arr[0:mid])
        a2 = mergeSort(arr[mid:len(arr)])
        return merge(a1, a2)

with open("input1.txt","r") as file:
  lst = file.readline()
  arr =  file.readline().split(" ")
  for i in range(len(arr)):
    arr[i] = int(arr[i])
  sorted_arr = mergeSort(arr)
  with open("outpu1.txt","w") as file:
    for j in sorted_arr:
      file.write(f"{j} ")