# -*- coding: utf-8 -*-
"""lab5 task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AebXEzU4RUwgq3TRy5MDehmVFcWIYe8F
"""

#Task_3

def DFS1(n,g,v,s):  
    v[n]=True
    for i in g[n]:
        if not v[i]:
            DFS1(i,g,v,s)
    s.append(n)

def DFS2(n,g,v,c):   
    v[n]=True
    c.append(n)
    for i in g[n]:
        if not v[i]:
            DFS2(i,g,v,c)
def K(N,g):
    v=[False]*(N+1)
    s=[]
    for n in range(1,N+1):
        if not v[n]:
            DFS1(n,g,v,s)
    rg={j:[] for j in range(1,N+1)}   
    for n in range(1,N+1):
        for i in g[n]:
            rg[i].append(n)
    v=[False]*(N+1)
    lst=[]
    while s:
        n=s.pop()
        if not v[n]:
            c=[]
            DFS2(n,rg,v,c)
            lst.append(c)
    return lst
with open("input3.txt","r") as file:
  N,M=map(int,file.readline().split())
  g={j:[] for j in range(1,N+1)}
  for j in range(M):
      u,v=map(int,file.readline().split())
      g[u].append(v)
  scc=K(N,g)  
with open("output3.txt","w") as file:
  for c in scc:
      x=' '.join(map(str,c))
      file.write(x+'\n')