# -*- coding: utf-8 -*-
"""Lab 5 task 1a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fsBUz-6beWNfw1S2zGRdjyJ5zaUtc5j3
"""

#Task_1A

def find_order(n, prerequisites):
    graph = [[] for _ in range(n + 1)]
    in_degree = [0] * (n + 1)

    for a, b in prerequisites:
        graph[a].append(b)
        in_degree[b] += 1

    stack = [i for i in range(1, n + 1) if in_degree[i] == 0]
    order = []

    while stack:
        node = stack.pop(0)
        order.append(node)

        for neighbor in graph[node]:
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0:
                stack.append(neighbor)

    if len(order) != n:
        return "IMPOSSIBLE"
    else:
        return order

with open("input1a.txt", 'r') as file:
    n, m = map(int, file.readline().split())
    prerequisites = [tuple(map(int, file.readline().split())) for _ in range(m)]

result = find_order(n, prerequisites)

with open("output1a.txt", 'w') as file:
    if isinstance(result, str):
        file.write(result)
    else:
        file.write(" ".join(map(str, result)))