# -*- coding: utf-8 -*-
"""lab5 task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GyWFOjZBDcc7w9rrdVLlT4RDGK_zIsFF
"""

#Task_2

from queue import PriorityQueue
def BFS(N,pre):
    g={}
    deg=[0]*(N+1)
    for x in range(1,N+1):
        g[x]=[]
    for A,B in pre:
        g[A].append(B)
        deg[B]+=1
    q=PriorityQueue()
    for y in range(1,N+1):
        if deg[y]==0:
            q.put(y)
    final=[]
    while not q.empty():
        y=q.get()
        final.append(y)
        for z in g[y]:
            deg[z]-=1
            if deg[z]==0:
                q.put(z)
    if len(final)==N:
        return final
    else:
         return []
with open("input2.txt","r") as file:
  N,M=map(int,file.readline().split())
  pre=[list(map(int,file.readline().split())) for j in range(M)]
  final=BFS(N,pre)
with open("output2.txt","w") as file:
  if len(final)==N:
      empty=""
      for k in final:
          empty+=str(k)+" "
      file.write(empty)
  else:
      empty='IMPOSSIBLE'
      file.write(empty)