# -*- coding: utf-8 -*-
"""lab5 task1b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XLMdkr5A7OWJsMqUaXotKVvRah7iu_y_
"""

#Task_1B

def BFS(N,pre):
    g={}
    deg=[0]*(N+1)
    for x in range(1,N+1):
        g[x]=[]
    for A,B in pre:
        g[A].append(B)
        deg[B]+=1
    q=[]
    for y in range(1,N+1):
        if deg[y]==0:
            q.append(y)
    final=[]
    while q:
        y=q.pop(0)
        final.append(y)
        for z in g[y]:
            deg[z]-=1
            if deg[z]==0:
                q.append(z)
    if len(final)==N:
        empty=""
        for i in final:
            empty+=str(i)+" "
        file.write(empty)
    else:
        empty="IMPOSSIBLE"
        file.write(empty)
with open("input1b.txt", 'r') as file:
  N,M=map(int,file.readline().split())
  pre=[tuple(map(int,file.readline().split())) for j in range(M)]
  with open("output1b.txt", 'w') as file:
    BFS(N,pre)