# -*- coding: utf-8 -*-
"""task2(2) lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dfQIjIaybJIj-M3pR9HGpvACBzWXh9xc
"""

with open("input2(2).txt", "r") as abc:
    def turn(arr):
        for i in range(len(arr)):
            arr[i] = int(arr[i])
        return arr
    def merge(a, b):
        i = 0
        j = 0
        l = []
        while i < len(a) and j < len(b):
            if a[i] <= b[j]:
                l.append(a[i])
                i += 1
            else:
                l.append(b[j])
                j += 1
        if i < len(a):
            l += a[i:]
        if j < len(b):
            l += b[j:]
        return l
    var = abc.read().split("\n")[0:]
    output = open("output2(2).txt", "w")
    s1 = var[1].split()
    arr1 = turn(s1)
    s2 = var[3].split()
    arr2 = turn(s2)
    sorted_arr = merge(arr1, arr2)
    for elem in sorted_arr:
        output.write(f"{elem} ")