# -*- coding: utf-8 -*-
"""task2(1) lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15IdEZSeJ5cVwoyMwWnM2YlY1n_8Rrx6s
"""

with open("input2(1).txt","r") as file:
  output =open("output2(1).txt","w")
  li = file.readlines()
  num1 = int(li[0])
  arr1 =li[1].split()
  num2 = int(li[2])
  arr2= li[3].split()
  new_arr = arr1+arr2
  arr = []
  for i in new_arr:
    arr.append(int(i))
  arr.sort()
  for i in arr:
    output.write(f"{int(i)} ")