# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UnMVRR1STYBCvuRKx7L-N5b4eTyqjP8v
"""

def arra(stri):
  ara = [0]* len(stri)
  for i in range(len(stri)):
    ara[i] = int(stri[i])
  return ara

with open("input3.txt","r") as file:
  number= file.readlines()
  id = arra(number[1].split(" "))
  marks = arra(number[2].split(" "))

for i in range(len(marks)):
  max_marks = marks[i]
  max_index = i
  for j in range(i+1,len(marks)):
    if marks[j]> max_marks:
      max_marks = marks[j]
      max_index = j
    if marks[j] == max_marks:
      if id[j]> id[i]:
        max_marks = marks[j]
        max_index = j
      else:
        max_marks = marks[i]
        max_index = i
  temp = marks[i]
  marks[i] = marks[max_index]
  marks[max_index] = temp

  temp_id = id[i]
  id[i] = id[max_index]
  id[max_index] = temp_id
dic = {}
for i in range(len(marks)):
  if marks[i] in dic:
    dic[marks[i]].append(id[i])
  else:
    dic[marks[i]] = [id[i]]

for k,v in dic.items():
  for i in range(len(v)):
    with open("output3.txt","a") as file:
      file.write(f"ID: {min(v)} Mark: {k}\n")
      v.remove(min(v))