# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10fHlLiBuMsrZLsKuYykaV3rwzIdETeqJ
"""

with open("input1a.txt","r") as file:
  number= file.readlines()
  for i in number[1:len(number)]:
    num = int(i)
    with open("output1a.txt","a") as file:
      if num %2 == 0:
        file.write(f"{num} is an Even number.\n")
      else:
        file.write(f"{num} is an Odd number.\n")