# -*- coding: utf-8 -*-
"""task1b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AclVNCx7zb3iW8LrkC_q7DftQqC_4gJU
"""

def calculation(x,opr,y):
  if opr == "+":
    return int(x) + int(y)
  if opr == "-":
    return int(x) - int(y)
  if opr == "*":
    return int(x) * int(y)
  if opr == "/":
    return int(x) / int(y)


with open("input1b.txt","r") as file:
  number= file.readlines()
  for i in number[1:len(number)]:
    z = i.split(" ")
    with open("output1b.txt","a") as file:
      result = calculation(z[1],z[2],z[3])
      file.write(f"The result of {int(z[1])} {z[2]} {int(z[3])} is {result}\n")