# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nyiNDjvZFI9_S6wjYX8BETudQxcBQw_D
"""

with open("input4.txt", "r") as file:
    l = file.readline().split(" ")
    output = open("output4.txt", "w")
    dic = {}
    for i in range(int(l[0])):
      z = file.readline().split(" ")
      dic[int(z[0])] = int(z[1])
    sorted_dict = dict(sorted(dic.items(), key=lambda x:x[1]))
    person = []
    person1 = []
    person2 = []
    idx = 0
    count=0
    for k,v in sorted_dict.items():
      if idx< int(l[1]):
        person.append([k,v])
        idx+=1
        count+=1
      if idx>=int(l[1]):
        if int(l[1]) == 2:
          if k>=person[0][0] and k>=person[0][1]:
            person[0] = [k,v]
            count+=1
          elif k>=person[1][0] and k>=person[1][1]:
            person[1]= [k,v]
            count+=1
        if int(l[1]) == 3:
          if k>=person[0][0] and k>=person[0][1]:
            person[0] = [k,v]
            count+=1
          elif k>=person[1][0] and k>=person[1][1]:
            person[1]= [k,v]
            count+=1
          elif k>=person[2][0] and k>=person[2][1]:
            person[2]= [k,v]
            count+=1
    output.write(str(count))