# -*- coding: utf-8 -*-
"""task4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLnXzdCfInX9q-5BMR62wfskmmBugUfl
"""

import math
file1 = open("/content/input4.txt",'r')
file2 = open("/content/output4.txt", 'w')

type, target = map(int, file1.readline().strip().split())
coins = list(map(int, file1.readline().strip().split()))

def Min_Coin_Change(type, target, coins):
    if target == 0:
        return 0
    if target < 0:
        return math.inf
    if type <= 0 and target >= 1:
        return math.inf
    return min(Min_Coin_Change(type-1, target, coins), 1 + Min_Coin_Change(type, target-coins[type-1], coins))
if Min_Coin_Change(type, target, coins) == math.inf:
    file2.write("-1")
else:
    file2.write(str(Min_Coin_Change(type, target, coins)))
file1.close()
file2.close()