# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IcIybn5Ka8YRiJYS38bXgFAmZyFPQeGb
"""

file1 = open("/content/input1.txt", 'r')
file2 = open("/content/output1.txt", 'w')

def find_representative(a):
  if parent[a] == a:
    return a
  return find_representative(parent[a])


def union(a, b):
  u = find_representative(a)
  v = find_representative(b)
  if u != v:
    parent[u] = v
    circle[v] += circle[u]

  file2.write(str(circle[v]) + '\n')


person, query = map(int, file1.readline().split())
parent = [ i for i in range(person) ]
circle = [ 1 for i in range(person) ]

for i in range(query):
  a, b = map(int, file1.readline().split())
  union(a, b)

file1.close()
file2.close()