# -*- coding: utf-8 -*-
"""task3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afw4WP5o1rX7n0rPBjnsQGa2vCT4aGUj
"""

file1 = open("/content/input3.txt",'r')
file2 = open("/content/output3.txt", 'w')
fredy = int(file1.readline().strip())
arr = [ 0 for x in range(fredy+1)]
def Jump_Count(n):
    if n == 0:
        return 0
    if n == 1:
        return 1
    if n == 2:
        return 2
    if n == 3:
        return 3

    if arr[n] == 0:
        arr[n] = Jump_Count(n-1) + Jump_Count(n-2)
    return arr[n]

file2.write(str(Jump_Count(fredy)))

file1.close()
file2.close()