# -*- coding: utf-8 -*-
"""lab4 task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10eh-BPySLLzEvDRmpSIFEIX1wMdT5OR_
"""

with open("input2.txt","r") as file:
  var = file.readline().split()
  n,m = int(var[0]) , int(var[1])
  dic = {}
  for i in range(1,m+1):
    var2 = file.readline().split(" ")
    p,c = int(var2[0]) , int(var2[1])
    if p not in dic:
      dic[i] = []
      dic[p] = [c]
    else:
      dic[p].append(c)
  visited = []
  queue = []
  travers = []
  def BFS(visited,queue,first):
    visited.append(first)
    queue.append(first)
    while queue:
      m = queue.pop(0)
      travers.append(m)
      if m in dic.keys():
        for values in dic[m]:
          if values not in visited:
            visited.append(values)
            queue.append(values)

  for k,v in dic.items():
    first = k
    break
  BFS(visited,queue,first)
  with open("output2.txt","w") as file:
    for i in travers:
      file.write(f"{str(i)} ")