# -*- coding: utf-8 -*-
"""Lab4 task1b

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xs4eq4QcSV6MHEgWIZUT7jleMXUibSX8
"""

with open("input1b.txt","r") as file:
  var1 = file.readline().split(" ")
  n = int(var1[0])
  m = int(var1[1])
  lst = [0]*(n+1)
  for i in range(m):
    var = file.readline().split()
    n1 = int(var[0])
    n2 = int(var[1])
    n3 = int(var[2])
    if lst[n1] == 0:
      lst[n1] = [(n2,n3)]
    else:
      lst[n1].append((n2,n3))
with open("output.1b","w") as file:
  for j in range(len(lst)):
    if lst[j] == 0:
      file.write(f"{j} : \n")
    else:
      file.write(f"{j} : ")
      for k in lst[j]:
        file.write(f"{k} ")
      file.write("\n")