# -*- coding: utf-8 -*-
"""lab4 task3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GTnqgNgJvUFPSXxOvza85KL-2_53PXHF
"""

with open("input3.txt","r") as file:
  var = file.readline().split()
  n,m = int(var[0]) , int(var[1])
  dic = {}
  for i in range(1,n+1):
    dic[i] = []
  for j in range(1,m+1):
    var2 = file.readline().split(" ")
    p,c = int(var2[0]) , int(var2[1])
    dic[p].append(c)
  visited = []
  travers =[]
  def DFS(visited,first):
    if first not in visited:
      visited.append(first)
      travers.append(first)
      for values in dic[first]:
          DFS(visited,values)

  for k,v in dic.items():
    first = k
    break
  DFS(visited,first)
  with open("output3.txt","w") as file:
    for i in travers:
      file.write(f"{str(i)} ")
