# -*- coding: utf-8 -*-
"""Lab4 task1a

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mippYE-ByDjBpybFb8tPF5GATckSYqPF
"""

with open("input1a.txt","r") as file:
  var1 = file.readline().split(" ")
  n = int(var1[0])
  m = int(var1[1])
  multi = []
  for i in range(n+1):
    lst = []
    for j in range(n+1):
      lst.append(0)
    multi.append(lst)
  for s in range(m):
    value = file.readline().split(" ")
    multi[int(value[0])][int(value[1])] = int(value[2])
  with open("output1a.txt","w") as file:
    for k in multi:
      for j in k:
        file.write(str(j) + " ")
      file.write("\n")