# -*- coding: utf-8 -*-
"""lab4 task6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PPkSZXv_WQ0gUtsgk91YE83sDNl0srSK
"""

import numpy as np
with open("input6.txt","r") as file:
  r,c = [int(i) for i in file.readline().split(" ")]
  matrix = np.zeros((r,c),dtype=str)
  maxd = 0
  for i in range(r):
    x = file.readline()
    for j in range(c):
      matrix[i][j] = x[j]

  def dfs(row,col,matrix):
    if row < 0 or row >=len(matrix) or col < 0 or col >= len(matrix[0]):
      return 0
    if matrix[row][col] == "#":
      return 0
    total = 0
    if matrix[row][col] == "D":
      total += 1
    matrix[row][col] = "#"
    total += dfs(row+1,col,matrix)
    total += dfs(row,col+1,matrix)
    total += dfs(row-1,col,matrix)
    total += dfs(row,col-1,matrix)
    return total

  def traverse(matrix,r,c,maxd):
    for row in range(r):
      for col in range(c):
        if matrix[row][col] == ".":
          a= dfs(row,col,matrix)
          if a > maxd:
            maxd = a
    return maxd
with open("output6.txt","w") as file:
  file.write(f"{traverse(matrix,r,c,maxd)}")