# -*- coding: utf-8 -*-
"""lab4 task5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16y0C2tVdxL4LqYlLe3rgunfDNWqAxIJX
"""

with open("input5.txt","r") as file:
  var = file.readline().split()
  cities = int(var[0])
  roads = int(var[1])
  des = int(var[2])
  graph = {}
  for i in range(cities + 1):
    graph[i] = []

  for _ in range(roads):
    u, v = map(int, file.readline().split())
    graph[u].append(v)
    graph[v].append(u)

  color = [0] * (cities + 1)
  parent = [-1] * (cities + 1)
  queue = []


  queue.append(1)
  color[1] = 1


  while queue:
    m = queue.pop(0)
    for neighbor in graph[m]:
      if color[neighbor] == 0:
        queue.append(neighbor)
        color[neighbor] = 1
        parent[neighbor] = m


  shortest_path = []
  current_city = des
  while current_city != -1:
    shortest_path.append(current_city)
    current_city = parent[current_city]


  str1 = ""
  for i in range(len(shortest_path)-1,-1,-1):
      str1 += str(shortest_path[i])+" "
  with open("output5.txt","w") as file:
    file.write(f"Time: {len(shortest_path)-1}\n")
    file.write(f"Shortest Path: {str1}")