# -*- coding: utf-8 -*-
"""lab4 task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17dNHiIY_fK_nHuPmyipr9-RMjGiNQuTq
"""

def isCyclic(n,dic):
  visited = [False]*n
  helper = [False]*n
  for i in range(1,n):
    if visited[i] == False:
      check = DFS(i,visited,helper,dic)
      if check == True:
        return True
  return False

def DFS(i,visited,helper,dic):
  visited[i] = True
  helper[i] = True
  neighbour = dic[i]
  for j in range(len(neighbour)):
    current = neighbour[j]
    if helper[current] == True:
      return True
    if visited[current] == False:
      check = DFS(current,visited,helper,dic)
      if check == True:
        return True
  helper[i] = False
  return False



with open("input4.txt","r") as file:
  var = file.readline().split()
  n,m = int(var[0]) , int(var[1])
  dic = {}
  for i in range(1,n+1):
    dic[i] = []
  for j in range(1,m+1):
    var2 = file.readline().split(" ")
    p,c = int(var2[0]) , int(var2[1])
    dic[p].append(c)
  cyclic = isCyclic(n+1,dic)
  with open("output4.txt","w") as file:
    if cyclic == True:
      file.write("YES")
    else:
      file.write("NO")