# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15G-BgMWe2WdqNBZp1TFHwBmXhS5mn1QX
"""

def timeChange(mini):
    t_time=mini.split(":")
    hr=int(t_time[0])
    minu = int(t_time[1])
    total_time = (hr*60)+minu
    return total_time
with open("input4.txt", "r") as file:
  n = file.readlines()
  train_lst = n[1:]
  for i in range(len(train_lst)):
    for j in range(len(train_lst)-1):
      train1 = train_lst[j].split(" ")
      time = train1[6]
      time1 = timeChange(time)
      train2 = train_lst[j+1].split(" ")
      time2 = timeChange(train2[6])
      if train1[0]>train2[0]:
        temp = train_lst[j]
        train_lst[j]= train_lst[j+1]
        train_lst[j+1]=temp
      if train1[0]==train2[0]:
        if time1<time2:
          temp = train_lst[j]
          train_lst[j]= train_lst[j+1]
          train_lst[j+1]=temp
with open("output4.txt","a") as file:
  for elem in train_lst:
    file.write(f"{elem}")