# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1er6JgRPY8wCeS-DXq6965nkDRkF5rhA4
"""

with open("input2.txt","r") as file:
  num=file.readlines()
  dumm_array = num[1].split(" ")
  array = [0]*len(dumm_array)
  for i in range(len(array)):
    array[i] = int(dumm_array[i])

  def bubbleSort(arr):
    flag=False
    for i in range(len(arr)-1):
        for j in range(len(arr)-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                flag=True
        if flag==False:
          break
    return arr
  with open("output2.txt","w") as file:
    arr=bubbleSort(array)
    file.write(f"{array}")

  #EXPLAINATION:
##In order to make it O(n) for the best case scenerio, I had to make sure that the loop ends after checking if the array is sorted from the start. So I used flag to make sure that if no swap has happened in
# the first iteration then we can say that the array is already sorted hence the loop will break and the array will be returned